name: Build Flutter APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest  # Use stable Ubuntu 22.04 runner

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3.6.0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: '3.19.6'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: milk_delivery_apk
          path: build/app/outputs/flutter-apk/app-release.apk
